language: java
jdk: 
  - oraclejdk8
before_install:
  - ./download_libs
  - ./install_dymola_libs
  - ./install_hades_integration_libs
  - ./install_helmflow_integration_libs
  - ./install_ipst_libs
  - ./install_openmodelica_libs
