#!/bin/bash

rm -rf ./temp_libs
mkdir -p ./temp_libs
cd ./temp_libs
../download_libs
../install_dymola_libs
../install_hades_integration_libs
../install_helmflow_integration_libs
../install_ipst_libs
../install_openmodelica_libs
cd ..
rm -rf ./temp_libs
