#!/bin/bash

# Optimize start JIT compilation in Java virtual machine for short run 
export MAVEN_OPTS="-XX:+TieredCompilation -XX:TieredStopAtLevel=1"

function exec_tool {
	export MAIN_CLASS="org.power_systems_modelica.psm.tools.Main"
	mvn exec:java --projects tools -Dexec.mainClass=$MAIN_CLASS -Dexec.args="$*" -Ditesla.config.dir=$PSM_DATA/test/cfg
}

# Samples

function mo2dyd {
	# Extract dynamic data definitions (to set-up a dynamic data repository) from an existing Modelica file
	MODELICA_FILE=$1
	DDR_LOCATION=$2
	mkdir -p $DDR_LOCATION
	exec_tool mo2dyd --modelicaFile $MODELICA_FILE --ddrLocation $DDR_LOCATION
}

exec_tool "$*"
#mo2dyd $PSM_DATA/test/ieee14/itesla/ieee14bus_no_loadflow.mo $PSM_DATA/tmp/ddr_ieee14 
