#!/bin/bash
rm -rf temp_ipst
mkdir -p temp_ipst
cd temp_ipst
git clone https://github.com/itesla/ipst-core.git
git clone https://github.com/itesla/ipst.git
cd ipst-core
mvn clean install -DskipTests
cd ipst
mvn clean install -DskipTests
cd ../..
rm -rf temp_ipst
