#!/bin/bash
#
# Copyright (c) 2017 - 2018, RTE (http://www.rte-france.com)
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# @author Luma Zamarreño <zamarrenolm at aia.es>
#

rm -rf temp_powsybl
mkdir -p temp_powsybl
cd temp_powsybl
git clone https://github.com/powsybl/powsybl-core.git
cd powsybl-core
git checkout tags/v1.0.0
mvn clean install -DskipTests
cd ..
cd ..
rm -rf temp_powsybl
