#!/bin/bash

rm -rf ./temp_libs
mkdir -p ./temp_libs
cd ./temp_libs
../scripts/download_libs
../scripts/install_dymola_libs
../scripts/install_hades_integration_libs
../scripts/install_helmflow_integration_libs
../scripts/install_ipst_libs
../scripts/install_openmodelica_libs
cd ..
rm -rf ./temp_libs
