#!/bin/bash

# Dymola and OpenModelica
wget https://dl.dropboxusercontent.com/u/41536604/psm_all_libs/dymola_interface-2016.jar
wget https://dl.dropboxusercontent.com/u/41536604/psm_all_libs/modelica_java.jar

# Hades
wget https://dl.dropboxusercontent.com/u/41536604/psm_all_libs/adn-export-0.1.jar
wget https://dl.dropboxusercontent.com/u/41536604/psm_all_libs/hades2-integration-0.1.jar

# HELM Flow
wget https://dl.dropboxusercontent.com/u/41536604/psm_all_libs/helmflow-api-0.1-SNAPSHOT.jar
wget https://dl.dropboxusercontent.com/u/41536604/psm_all_libs/helmflow-api-impl-0.1-SNAPSHOT.jar
wget https://dl.dropboxusercontent.com/u/41536604/psm_all_libs/helmflow-ipst-integration-0.1-SNAPSHOT.jar
wget https://dl.dropboxusercontent.com/u/41536604/psm_all_libs/helmflow_core-2.2.4.201606211030.0.jar
wget https://dl.dropboxusercontent.com/u/41536604/psm_all_libs/helmflow_core-2.2.5.201702061800.0.jar

# iPST
wget https://dl.dropboxusercontent.com/u/41536604/psm_all_libs/commons-0.1-SNAPSHOT.jar

wget https://dl.dropboxusercontent.com/u/41536604/psm_all_libs/iidm-network-api-0.1-SNAPSHOT.jar
wget https://dl.dropboxusercontent.com/u/41536604/psm_all_libs/iidm-network-impl-0.1-SNAPSHOT.jar
wget https://dl.dropboxusercontent.com/u/41536604/psm_all_libs/iidm-converter-api-0.1-SNAPSHOT.jar
wget https://dl.dropboxusercontent.com/u/41536604/psm_all_libs/iidm-xml-converter-0.1-SNAPSHOT.jar

wget https://dl.dropboxusercontent.com/u/41536604/psm_all_libs/cim1-import-0.1-SNAPSHOT.jar
wget https://dl.dropboxusercontent.com/u/41536604/psm_all_libs/cim1-model-0.1-SNAPSHOT.jar

wget https://dl.dropboxusercontent.com/u/41536604/psm_all_libs/loadflow-api-0.1-SNAPSHOT.jar
wget https://dl.dropboxusercontent.com/u/41536604/psm_all_libs/contingency-api-0.1-SNAPSHOT.jar

wget https://dl.dropboxusercontent.com/u/41536604/psm_all_libs/online-workflow-0.1-SNAPSHOT.jar
wget https://dl.dropboxusercontent.com/u/41536604/psm_all_libs/computation-0.1-SNAPSHOT.jar
wget https://dl.dropboxusercontent.com/u/41536604/psm_all_libs/computation-local-0.1-SNAPSHOT.jar
wget https://dl.dropboxusercontent.com/u/41536604/psm_all_libs/entsoe-util-0.1-SNAPSHOT.jar
wget https://dl.dropboxusercontent.com/u/41536604/psm_all_libs/graph-0.1-SNAPSHOT.jar
