#!/bin/bash
#
# Copyright (c) 2017 - 2018, RTE (http://www.rte-france.com)
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# @author Luma Zamarreño <zamarrenolm at aia.es>
#


rm -rf ./temp_libs
mkdir -p ./temp_libs
cd ./temp_libs
../scripts/download_libs
../scripts/install_dymola_libs
../scripts/install_hades_integration_libs
../scripts/install_helmflow_integration_libs
../scripts/install_powsybl_libs
../scripts/install_openmodelica_libs
cd ..
rm -rf ./temp_libs
