#!/bin/bash

echo "=== SUREFIRE REPORTS ==="
echo ""
for SRD in `find . -name "surefire-reports" -type d`
do
	echo "SUREFIRE REPORTS folder $SRD"
	echo ""
    for SRF in $SRD/*xml
	do
		echo "SUREFIRE REPORT file $SRF"
		cat $SRF
		echo ""
	done
done
