#!/bin/bash

VERSION=0.1-SNAPSHOT
PLUGIN="org.apache.maven.plugins:maven-install-plugin:2.5.2:install-file"

function install_one_file {
	mvn ${PLUGIN} -Dfile=$1-${VERSION}.jar 
}

install_one_file cim1-import 
install_one_file cim1-model 
install_one_file commons 
install_one_file computation
install_one_file computation-local
install_one_file iidm-api 
install_one_file iidm-impl 
install_one_file iidm-converter-api
install_one_file iidm-xml-converter 
install_one_file loadflow-api 
install_one_file contingency-api 
install_one_file online-workflow
install_one_file entsoe-util
install_one_file math
