#!/bin/bash
#
# Copyright (c) 2017 - 2018, RTE (http://www.rte-france.com)
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# @author Luma Zamarreño <zamarrenolm at aia.es>
#


rm -rf ./temp_libs
mkdir -p ./temp_libs
cd ./temp_libs

# Previously we had the list of libraries in the script that was downloading them ...
# for l in $( grep "^wget" ../scripts/download_libs | sed 's/^.*\///' );  do
# Now we rely on a text file (all libraries are downloaded from a single zip file)
for l in $( cat ../scripts/libs.txt );  do
	if [[ -n $(find ~/.m2/repository -name $l -not -path "*/power-systems-modelica/*" -print -exec cp {} . \;) ]];
	then
		echo "lib     $l";
	else
		echo "MISSING $l";
	fi 
done
