#!/bin/bash
export MAIN_CLASS="org.power_systems_modelica.psm.gui.MainApp"
mvn exec:java --projects gui -Dexec.mainClass=$MAIN_CLASS -Dexec.args="$*" -Ditesla.config.dir=$PSM_DATA/test/cfg | tee psm.log
