#!/bin/bash
#
# Copyright (c) 2017 - 2018, RTE (http://www.rte-france.com)
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# @author Luma Zamarreño <zamarrenolm at aia.es>
#



export MAIN_CLASS="org.power_systems_modelica.psm.gui.MainApp"
mvn exec:java --projects gui -Dexec.mainClass=$MAIN_CLASS $* -Ditools.config.dir=$PSM_DATA/cfg | tee psm.log
